# Generated by Django 4.0.3 on 2023-05-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_history', '0002_remove_violationhistory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationhistory',
            name='fee',
            field=models.FloatField(default=5000000),
        ),
    ]
