# Generated by Django 4.0.3 on 2023-05-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violation_history', '0004_violationhistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationhistory',
            name='location',
        ),
    ]
