# Generated by Django 4.0.3 on 2023-05-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_image'),
        ('violation_history', '0006_alter_violationhistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationhistory',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
    ]
