# Generated by Django 4.0.3 on 2023-05-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_history', '0007_alter_violationhistory_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsureViolationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='unsureviolation/')),
            ],
        ),
    ]
