# Generated by Django 4.0.3 on 2023-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_history', '0009_violation_remove_violationhistory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsureviolationhistory',
            name='description',
            field=models.CharField(default='Possible red light runner', max_length=200),
        ),
    ]
