# Generated by Django 4.0.3 on 2023-06-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_history', '0010_alter_unsureviolationhistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='fee',
            field=models.FloatField(default=500000),
        ),
    ]
