# Generated by Django 4.0.3 on 2023-06-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_history', '0011_alter_violation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsureviolationhistory',
            name='wide_image',
            field=models.ImageField(blank=True, null=True, upload_to='wideimage/'),
        ),
        migrations.AddField(
            model_name='violationhistory',
            name='wide_image',
            field=models.ImageField(blank=True, null=True, upload_to='violation/'),
        ),
    ]
